# Generated by Django 3.1.7 on 2021-06-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='parent',
        ),
    ]
