# Generated by Django 3.1.7 on 2021-06-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tree_id',
        ),
    ]
