# Generated by Django 3.1.7 on 2021-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210517_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
