# Generated by Django 3.1.7 on 2021-05-19 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210517_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
