# Generated by Django 3.1.7 on 2021-05-20 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210520_0311'),
        ('home', '0007_auto_20210519_2037'),
    ]

    operations = [
    ]
