# Generated by Django 3.1.7 on 2021-06-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='stok_durum',
            new_name='amount',
        ),
    ]
